import project.com.controller.AreaController
import project.com.controller.BorrowerController
import project.com.controller.CityController
import project.com.controller.ComplainController
import project.com.controller.DatasetController
import project.com.controller.FeedbackController
import project.com.controller.LenderController
import project.com.controller.LoanApplicationController
import project.com.controller.LoanDetailController
import project.com.controller.LoginController
import project.com.controller.ScrapingController
